DROP TABLE `USER_GROUPS`;
DROP TABLE `USER_ACCOUNTS`;
DROP TABLE `CODES`;
DROP TABLE `CODE_GROUPS`;
DROP TABLE `USERS`;

SHOW TABLES;

CREATE TABLE `CODE_GROUPS` (
	`code_group_id`	INT	NOT NULL AUTO_INCREMENT,
	`code_group_name`	VARCHAR(255)	NOT NULL,
	`display_order`	TINYINT	NOT NULL,
	`is_use`	TINYINT	NOT NULL	DEFAULT 1,
	`created_at`	TIMESTAMP NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`created_by`	INT	NOT NULL,
	`modified_at`	TIMESTAMP NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`modified_by`	INT	NOT NULL,
	`parent_id`	INT	NULL,
	`code_type`	TINYINT	NOT NULL DEFAULT 1,
  `code_value_type` TINYINT NOT NULL DEFAULT 1,
	`code_order_field`	VARCHAR(255)	NULL,
  `memo` TEXT NULL,
  CONSTRAINT `PK_CODE_GROUPS` PRIMARY KEY (`code_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- ALTER TABLE `CODE_GROUPS` ADD `code_value_type` TINYINT DEFAULT 1 AFTER `code_type`;
-- ALTER TABLE `CODE_GROUPS` ADD `memo` TEXT;

CREATE TABLE `CODES` (
	`code_id`	INT	NOT NULL AUTO_INCREMENT,
	`code_group_id`	INT	NOT NULL,
	`code_name`	VARCHAR(255)	NOT NULL,
	`display_order`	TINYINT	NOT NULL,
	`is_use`	TINYINT	NOT NULL	DEFAULT 1,
	`is_default`	TINYINT	NOT NULL	DEFAULT 0,
	`code_value_string`	VARCHAR(255)	NULL,
	`code_value_int`	INT	NULL,
	`created_at`	TIMESTAMP NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`created_by`	INT	NOT NULL,
	`modified_at`	TIMESTAMP NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`modified_by`	INT	NOT NULL,
	`parent_id`	INT	NULL,
  `memo` TEXT NULL,
  CONSTRAINT `PK_CODES` PRIMARY KEY (`code_id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

-- ALTER TABLE `CODES` ADD `memo` TEXT;

CREATE TABLE `USERS` (
	`user_id`	INT	NOT NULL AUTO_INCREMENT,
	`user_name`	VARCHAR(50)	NOT NULL,
	`is_use`	TINYINT	NOT NULL	DEFAULT 1,
	`is_activate`	TINYINT	NOT NULL	DEFAULT 1,
	`created_at`	TIMESTAMP NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`modified_at`	TIMESTAMP NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `PK_USERS` PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE `USER_GROUPS` (
	`user_group_id`	INT	NOT NULL AUTO_INCREMENT,
	`user_id`	INT	NOT NULL,
	`group_code`	INT	NOT NULL	COMMENT '코드그룹(사용자그룹)',
	`is_use`	TINYINT	NOT NULL	DEFAULT 1,
  CONSTRAINT `PK_USER_GROUPS` PRIMARY KEY (`user_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE `USER_ACCOUNTS` (
	`account_id`	INT	NOT NULL AUTO_INCREMENT,
	`user_id`	INT	NOT NULL,
	`platform_code`	INT	NOT NULL,
	`login_id`	VARCHAR(255)	NOT NULL,
	`login_pwd`	VARCHAR(255)	NOT NULL	COMMENT 'SNS 계정의 경우 access token',
	`is_default`	TINYINT	NOT NULL	DEFAULT 1,
	`is_use`	TINYINT	NOT NULL	DEFAULT 1,
  CONSTRAINT `PK_USER_ACCOUNTS` PRIMARY KEY (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;


ALTER TABLE `CODE_GROUPS` ADD CONSTRAINT `FK_CODE_GROUPS_parentID_REF_CODE_GROUPS` FOREIGN KEY (`parent_id`) REFERENCES `CODE_GROUPS` (`code_group_id`);
ALTER TABLE `CODE_GROUPS` ADD CONSTRAINT `FK_CODE_GROUPS_createBy_REF_USERS` FOREIGN KEY (`created_by`) REFERENCES `USERS` (`user_id`);
ALTER TABLE `CODE_GROUPS` ADD CONSTRAINT `FK_CODE_GROUPS_modifiedBy_REF_USERS` FOREIGN KEY (`modified_by`) REFERENCES `USERS` (`user_id`);

ALTER TABLE `CODES` ADD CONSTRAINT `FK_CODES_codeGroupID_REF_CODE_GROUPS` FOREIGN KEY (`code_group_id`) REFERENCES `CODE_GROUPS` (`code_group_id`);
ALTER TABLE `CODES` ADD CONSTRAINT `FK_CODES_parentID_REF_CODES` FOREIGN KEY (`parent_id`) REFERENCES `CODES` (`code_id`);
ALTER TABLE `CODES` ADD CONSTRAINT `FK_CODES_createBy_REF_USERS` FOREIGN KEY (`created_by`) REFERENCES `USERS` (`user_id`);
ALTER TABLE `CODES` ADD CONSTRAINT `FK_CODES_modifiedBy_REF_USERS` FOREIGN KEY (`modified_by`) REFERENCES `USERS` (`user_id`);


ALTER TABLE `USER_ACCOUNTS` ADD CONSTRAINT `FK_USER_ACCOUNTS_userID_REF_USERS` FOREIGN KEY (`user_id`) REFERENCES `USERS` (`user_id`);
ALTER TABLE `USER_ACCOUNTS` ADD CONSTRAINT `FK_USER_ACCOUNTS_platformCode_REF_CODES` FOREIGN KEY (`platform_code`) REFERENCES `CODES` (`code_id`);

ALTER TABLE `USER_GROUPS` ADD CONSTRAINT `FK_USER_GROUPS_userID_REF_USERS` FOREIGN KEY (`user_id`) REFERENCES `USERS` (`user_id`);
ALTER TABLE `USER_GROUPS` ADD CONSTRAINT `FK_USER_GROUPS_groupCode_REF_CODES` FOREIGN KEY (`group_code`) REFERENCES `CODES` (`code_id`);

